### ISSUE TITLE
i installed it as you said but how to open it and download the tracks please tell.  i don't know programming.

### ISSUE THREAD

**Issue by KlingonMaster** [evan-goode/mania#13]

**Comment by evan-goode** [comment]
Hi! If you installed using the `pip` command in the README, you should be able to run it by typing `mania` in your terminal/command prompt. Try the first usage example from the README:
```
mania track the great gig in the sky
```
Keep in mind it's a command-line (terminal only) tool and there is no graphical windowed interface. If you're on Windows, this project has a GUI and might be more user-friendly:
https://github.com/yaronzz/Tidal-Media-Downloader-PRO

I might open a Matrix room for support/general discussion since GitHub issues aren't the best place for this.

**Comment by KlingonMaster** [comment]
After installing like this:
pip3 install --user --upgrade "https://github.com/evan-goode/mania/archive/master.zip"

i type mania in a fresh PowerShell console but it says:
-----------------------------------------------------------------------------------------
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Ankit> mania
mania : The term 'mania' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mania
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (mania:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Ankit>

**Comment by evan-goode** [comment]
It sounds like the directory (folder) where `pip --user` installs executable files is not listed in your system's `PATH` variable, so your shell can't find it. Running `python3 -m site --user-base` should show the path to the "user base directory" where Python puts all kinds of user-specific files. For example, on my system, this path is `/home/evan/.local`, but it will look different for you since you're on Windows. There is a folder inside that called `bin` which should contain an executable file called `mania`. You need to add this `bin` directory to your system `PATH` variable. In my case, the full path to the `bin` directory would be `/home/evan/.local/bin`.

See this article for help adding a directory to your `PATH`:
https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)
