### ISSUE TITLE
Need to set requirement prompt_toolkit==1.0.14

### ISSUE THREAD

**Issue by shillshocked** [evan-goode/mania#2]
Doesn't work on latest version of prompt_toolkit.

You can do this:
pip install 'prompt_toolkit==1.0.14'

Maybe better change the version of prompt_toolkit in requirements.txt:
prompt_toolkit==1.0.14

**Comment by evan-goode** [comment]
Thanks!
The problem comes from one of Mania's dependencies, [whaaaaat](https://github.com/finklabs/whaaaaat), and would be addressed by [this PR from August](https://github.com/finklabs/whaaaaat/pull/25). Hopefully, we can force whaaaaat to use an earlier version of prompt_toolkit by pinning it in Mania's setup.py, but I don't know how robust this solution will be.

Mania commit 515924f874b14a4f8859ce4361faf60b439b39f9 pins prompt_toolkit to 1.0.15, and it seems to work for me at least. Give it a try:

```
pip install --user --upgrade "https://github.com/evan-goode/mania/archive/master.zip"
```

I may want to switch out whaaaaat for something more actively maintained.

**Comment by evan-goode** [comment]
Swapped whaaaaat for [questionary](https://github.com/tmbo/questionary) in 63b87dafbee933837e39c8272b33c15d81890834.
