### ISSUE TITLE
How to add Year in the Album Title 

### ISSUE THREAD

**Issue by miiraheart** [evan-goode/mania#9]
Hi, I would like to know how to add the option for downloading the artist's albums including the year, as in the following format:

Artist-Name --> [201X] - Album Name --> Track Number - Artist Name - Song Name.

Thanks!

**Comment by evan-goode** [comment]
Hi! I just pushed a branch that should download tracks with that directory structure, check out 87b61023e01c03279d59efcb47accd4f9496a2fa.

For example:
```
mania album --full-structure --lucky in rainbows radiohead
```
will create
```
Radiohead/
└── [2007] - In Rainbows
    ├── 01 - Radiohead - 15 Step.flac
    └── 02 - Radiohead - Bodysnatchers.flac
...
```

The relevant function is `get_track_path` in `mania.py`.

I'm hesitant to add a ton of configuration options for changing the filename format and/or directory structure, since this project isn't meant to be an all-encompassing organization tool. That kind of thing is best left to other tools, like [beets](https://beets.io/).

**Comment by miiraheart** [comment]
Thank you so much for your help!
